version: "3"

services:
  app:
    container_name: golang-etl-case
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=docker
      - DB_NAME=golang-etl-case
    restart: unless-stopped

  postgres:
    container_name: postgres-golang
    image: postgres:11
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=golang-etl-case

volumes:
  db-data: